import Head from 'next/head';
import Image from 'next/image';

import Footer from '../components/Footer';
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rick Hekman, Creative Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
           Rick Hekman 
        </h1>        
        <p>Creative Developer</p>
        <div className={styles.avatar}>
          <Image 
            alt='Rick Hekman avatar'
            src='/images/rickhekman.webp'
            width={400}
            height={600}          
          />
        </div>
      </main>
      <Footer />
    </div>
  )
}
